# Generated by Django 3.1.7 on 2022-09-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20220909_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_needed', models.CharField(blank=True, max_length=50)),
                ('no_of_people', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.CharField(choices=[('Munchy Monday', 'Munchy Monday'), ('Tasty Tuesday', 'Tasty Tuesday'), ('Wow Wednesday', 'Wow Wednesday'), ('Toothsome Thursday', 'Toothsome Thursday'), ('Fries Friday', 'Fries Friday'), ('Saucy Saturday', 'Saucy Saturday'), ('Superbowl Sunday', 'Superbowl Sunday')], default='Munchy Monday', max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_food_order', to='app.food'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
