# Generated by Django 3.1.7 on 2022-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220909_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='no_of_people',
            new_name='no_of_plates',
        ),
    ]
