# Generated by Django 3.1.7 on 2022-09-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_foodorder_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='order_address',
            new_name='delivery_address',
        ),
    ]
