# Generated by Django 3.1.7 on 2022-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220909_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='date_needed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='no_of_plates',
            field=models.CharField(max_length=100),
        ),
    ]
