# Generated by Django 3.1.7 on 2022-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220909_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
