# Generated by Django 3.1.7 on 2022-09-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220909_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Refunded', 'Refunded')], default='Pending', max_length=50),
        ),
    ]
