# Generated by Django 3.1.7 on 2022-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_foodorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Incoming', 'Incoming'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Received', max_length=50),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
