# Generated by Django 3.1.7 on 2022-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220922_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='order_id',
            field=models.CharField(blank=True, default='no order id yet', max_length=20),
        ),
    ]
