# Generated by Django 4.1 on 2022-10-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_category_id_alter_event_id_alter_food_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="date_added",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="foodorder",
            name="date_needed",
            field=models.DateField(help_text="Date you need this order: dd/mm/yy"),
        ),
        migrations.AlterField(
            model_name="foodorder",
            name="delivery_address",
            field=models.TextField(
                default="Ondo",
                help_text="Please enter the full address for easy delivery.",
            ),
        ),
        migrations.AlterField(
            model_name="foodorder",
            name="menu",
            field=models.ForeignKey(
                help_text="Select meal.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_food_order",
                to="app.food",
            ),
        ),
        migrations.AlterField(
            model_name="foodorder",
            name="no_of_plates",
            field=models.CharField(
                help_text="How many many guest(s) owns this meal?", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="foodorder",
            name="order_id",
            field=models.CharField(
                blank=True, default="no order id yet", max_length=50
            ),
        ),
    ]
