# Generated by Django 4.1 on 2022-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_gallery_date_added_alter_foodorder_date_needed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="testimonial/")),
                ("testimony", models.CharField(blank=True, max_length=100)),
                ("profession", models.CharField(blank=True, max_length=50)),
                ("date_added", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(blank=True, upload_to="gallery/"),
        ),
    ]
