# Generated by Django 3.1.7 on 2022-09-03 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='media/default.jpeg', upload_to='users/')),
                ('gender', models.CharField(choices=[('Please select', 'Please select'), ('Male', 'Male'), ('Female', 'Female')], default='Please Select', max_length=100)),
                ('category', models.CharField(choices=[('Choose category', 'Choose category'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], default='Choose category', max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, default='Ondo', max_length=100)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('state', models.CharField(blank=True, default=100, max_length=200)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('subscribed_member', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
