# Generated by Django 4.1 on 2022-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, default="default.jpeg", upload_to="users"
            ),
        ),
    ]
